dist: trusty

language: node_js

env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null

matrix:
  fast_finish: true
  include:
    - node_js: "8"
      os: linux
      env: SCRIPT=lint
    - node_js: "8"
      os: linux
      env: SCRIPT=test

before_install:
  # Install yarn.
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn config set spin false
  - yarn config set progress false

script:
  - if [[ "$SCRIPT" ]]; then npm run $SCRIPT; fi
