version: 2

_defaults: &defaults
  working_directory: ~/ng
  docker:
    - image: angular/ngcontainer:0.0.5

_post_checkout: &post_checkout
  post: git pull --ff-only origin "refs/pull/${CI_PULL_REQUEST//*pull\//}/merge"

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: angular_devkit-{{ checksum "package-lock.json" }}

      - run: npm install --no-save
      - run: npm run lint

  validate:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: angular_devkit-{{ checksum "package-lock.json" }}

      - run: npm install --no-save
      - run: npm run validate

  test:
    <<: *defaults
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: angular_devkit-{{ checksum "package-lock.json" }}

      - run: npm install --no-save
      - run: npm run test -- --code-coverage --full

  integration:
    <<: *defaults
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: angular_devkit-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: angular_devkit-integration-simple-{{ checksum "tests/@angular_devkit/build_optimizer/webpack/simple-app/package-lock.json" }}
      - restore_cache:
          key: angular_devkit-integration-aio-{{ checksum "tests/@angular_devkit/build_optimizer/webpack/aio-app/package-lock.json" }}

      - run: npm install --no-save
      - run: xvfb-run -a npm run integration

      - save_cache:
          key: angular_devkit-integration-simple-{{ checksum "tests/@angular_devkit/build_optimizer/webpack/simple-app/package-lock.json" }}
          paths:
            - "tests/@angular_devkit/build_optimizer/webpack/simple-app/node_modules"
      - save_cache:
          key: angular_devkit-integration-aio-{{ checksum "tests/@angular_devkit/build_optimizer/webpack/aio-app/package-lock.json" }}
          paths:
            - "tests/@angular_devkit/build_optimizer/webpack/aio-app/node_modules"

  build:
    <<: *defaults
    steps:
      - checkout:
          <<: *post_checkout
      - restore_cache:
          key: angular_devkit-{{ checksum "package-lock.json" }}

      - run: bazel run @nodejs//:npm install
      - run: bazel build //packages/...

      - save_cache:
          key: angular_devkit-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"


workflows:
  version: 2
  default_workflow:
    jobs:
      - lint
      - validate
      - build
      - test
      - integration
